#!/bin/bash
README=".README.md"
README_API="api/README.md"
README_CLIENT="client/README.md"

end_section() {
    echo '' >> README.md
    echo '' >> README.md
}

echo Starting build-readme.sh
echo "<!--- This file is automatically generated. Don't edit! -->" > README.md

cat $README >> README.md
end_section

cat $README_API >> README.md
end_section

cat $README_CLIENT >> README.md
end_section

# Final
echo Completed build-readme.sh